export { McpModuleError } from "./mcp.errors.ts";
export type { McpModuleErrorCode } from "./mcp.errors.ts";
export {
	MCP_CATALOG_SCHEMAS_TOOL_NAME,
	MCP_CATALOG_SEARCH_TOOL_NAME,
	defineMcpCatalogExposureResolver,
} from "./mcp-catalog-exposure.ts";
export type {
	McpCatalogEagerExposure,
	McpCatalogExposureKind,
	McpCatalogExposureOptions,
	McpCatalogExposureResolver,
	McpCatalogExposureResolverInput,
	McpCatalogExposureStrategy,
	McpCatalogLazyExposure,
	McpCatalogNameSelector,
	McpCatalogPredicateSelector,
	McpCatalogReadonly,
	McpCatalogSchemasResult,
	McpCatalogSearchExposure,
	McpCatalogSearchResult,
	McpCatalogSearchResultTool,
	McpCatalogTagSelector,
	McpCatalogTool,
	McpCatalogToolSelector,
} from "./mcp-catalog-exposure.ts";
export { Prompt, Resource, Targets, Tool } from "./decorators/mcp-handler.decorators.ts";
export type {
	HandlerDefinition,
	PromptHandlerDefinition,
	PromptMethodDecorator,
	PromptOptions,
	ResourceHandlerDefinition,
	ResourceMethodDecorator,
	ResourceOptions,
	ToolHandlerDefinition,
	ToolMethodDecorator,
	ToolOptions,
	TypedMethodDecorator,
} from "./decorators/mcp-handler.decorators.ts";
export { McpHandlerRegistry } from "./discovery/mcp-handler.registry.ts";
export type { McpRegisteredHandler } from "./discovery/mcp-handler.registry.ts";
export { McpHttpController, McpHttpControllerFor } from "./mcp-http.controller.ts";
export type {
	McpHttpControllerClass,
	McpHttpControllerOptions,
	McpHttpHandlerFactory,
} from "./mcp-http.controller.ts";
export { McpFeatureModule, McpModule } from "./mcp.module.ts";
export type { McpForRootAsyncOptions, McpForRootOptions } from "./mcp.module-definition.ts";
export { McpRuntimeService } from "./mcp-runtime.service.ts";
export { createMcpHandlerPassthroughMiddleware } from "./mcp-handler.middleware.ts";
export { MCP_MODULE_OPTIONS } from "./mcp.tokens.ts";
export type {
	McpCapabilityMutation,
	McpCapabilityMutationKind,
	McpCapabilityMutationObserver,
	McpCapabilityMutationType,
	McpCapabilityVisibility,
	McpCapabilityVisibilityPolicy,
	McpDynamicHandlerRegistration,
} from "./mcp-capability.types.ts";
export type {
	McpFeatureOptions,
	McpHandlerAuthorizationPolicy,
	McpHandlerInvocationInput,
	McpHandlerInvocationOutput,
	McpHandlerInvocationOutputFor,
	McpHandlerInvocationOutputMap,
	McpHandlerLifecycleObserver,
	McpHandlerMiddleware,
	McpHandlerOperationContext,
	McpHandlerPassthroughMiddleware,
	McpModuleExtras,
	McpModuleOptions,
	McpNestGatewayOptions,
	McpNestGatewayUpstream,
	McpNestGatewayUpstreamDefinition,
	McpNestServerDefinition,
} from "./mcp.types.ts";

export {
	McpAuthorizationError,
	McpMiddlewareReentryError,
	allowMcpOperation,
	composeMcpLifecycleObservers,
	composeMcpMiddleware,
	createMcpAuthorizationMiddleware,
	createMcpLifecycleMiddleware,
	createMcpOperation,
	createMcpOperationContext,
	createMcpPassthroughMiddleware,
	denyMcpOperation,
	enforceMcpAuthorization,
	toMcpErrorDetails,
} from "@nestm/mcp-core";
export type {
	McpAttributeScalar,
	McpAttributeValue,
	McpAttributes,
	McpAuthorizationDecision,
	McpAuthorizationPolicy,
	McpErrorDetails,
	McpLifecycleEvent,
	McpLifecycleObserver,
	McpOperation,
	McpOperationContext,
	McpOperationHandler,
	McpOperationMiddleware,
	McpPassthroughMiddleware,
} from "@nestm/mcp-core";

export {
	AuthorizationServerMismatchError,
	Client,
	ClientCredentialsProvider,
	CrossAppAccessProvider,
	InsecureTokenEndpointError,
	InsufficientScopeError,
	IssuerMismatchError,
	MCP_CLIENT_NOT_CONNECTED,
	MCP_CLIENT_RUNTIME_CLOSED,
	MCP_CLIENT_SERVER_EXISTS,
	MCP_CLIENT_SERVER_NOT_FOUND,
	MCP_CLIENT_SHUTDOWN_TIMEOUT,
	McpClientRuntimeError,
	OAuthClientFlowError,
	PrivateKeyJwtProvider,
	RegistrationRejectedError,
	StaticPrivateKeyJwtProvider,
	StdioClientTransport,
	StreamableHTTPClientTransport,
	UnauthorizedError,
	McpClientRuntime,
	applyMiddlewares,
	auth,
	composeMcpFetchMiddleware,
	createDefaultMcpClientTransportFactory,
	createMcpClientPassthroughMiddleware,
	createMcpClientToolSchema,
	createMcpClientTransport,
	createMcpHttpClientTransport,
	defineMcpClientTransform,
	createPrivateKeyJwtAuth,
	createMcpStdioClientTransport,
	createMiddleware,
	discoverOAuthMetadata,
	discoverOAuthProtectedResourceMetadata,
	discoverOAuthServerInfo,
	isInputRequiredResult,
	refreshAuthorization,
	specTypeSchemas,
	withInputRequired,
	withLogging,
	withOAuth,
} from "@nestm/mcp-client";
export type {
	AddClientAuthentication,
	AuthOptions,
	AuthProvider,
	AuthResult,
	ClientAuthMethod,
	ClientCredentialsProviderOptions,
	ClientOptions,
	CallToolRequest,
	CallToolRequestOptions,
	CompleteRequest,
	CompleteResult,
	ConnectOptions,
	CrossAppAccessContext,
	CrossAppAccessProviderOptions,
	EmptyResult,
	GetPromptRequest,
	InputRequest,
	InputRequests,
	InputRequiredOptions,
	InputResponse,
	InputResponses,
	LoggingLevel,
	LoggingOptions,
	McpSubscription,
	Middleware,
	Notification,
	NotificationOptions,
	OAuthClientInformationContext,
	OAuthClientProvider,
	OAuthDiscoveryState,
	OAuthServerInfo,
	PriorDiscovery,
	ReadResourceRequest,
	Request,
	RequestMethod,
	RequestOptions,
	RequestTypeMap,
	ResultTypeMap,
	StandardSchemaV1,
	StdioServerParameters,
	StreamableHTTPClientTransportOptions,
	SubscriptionFilter,
	Transport,
} from "@nestm/mcp-client";
export type {
	McpClientConnectionSnapshot,
	McpClientConnectionState,
	McpClientAttributesResolver,
	McpClientConfigurationContext,
	McpClientConfigurator,
	McpClientMiddleware,
	McpClientMrtrMethod,
	McpClientMrtrRequest,
	McpClientMrtrRequestOptions,
	McpClientMrtrResult,
	McpClientOperationContext,
	McpClientOperationInput,
	McpClientPassthroughMiddleware,
	McpClientPrincipalResolver,
	McpClientProtocolRequest,
	McpClientReadonly,
	McpClientRequestMethod,
	McpClientRuntimeOptions,
	McpClientRuntimeErrorCode,
	McpClientServerDefinition,
	McpClientSubscription,
	McpClientTransportDefinition,
	McpClientTransportFactory,
	McpClientTransportFactoryContext,
	McpClientTransform,
	McpClientTransformInput,
	McpClientTransformOptions,
	McpClientTransformResult,
	McpClientTool,
	McpClientToolInputSchema,
	McpClientToolOutputSchema,
	McpClientToolSchemaIssue,
	McpClientToolSchemaResult,
	McpClientToolStandardSchema,
	McpHttpClientTransportDefinition,
	McpSdkClientFactory,
	McpSdkClientFactoryContext,
	McpStdioClientTransportDefinition,
} from "@nestm/mcp-client";
export {
	acceptedContent,
	completable,
	createRequestStateCodec,
	defineMcpServer,
	defineMcpServerFeature,
	fromJsonSchema,
	inputRequired,
	inputResponse,
	McpServer,
	McpServerRegistry,
	McpServerRuntime,
	McpServerRuntimeError,
	resolveMcpServerPrincipal,
	ResourceTemplate,
} from "@nestm/mcp-server";
export type {
	CallToolResult,
	CompletableSchema,
	CompleteCallback,
	CompleteResourceTemplateCallback,
	ElicitInputParams,
	GetPromptResult,
	InputRequiredSpec,
	InputRequiredResult,
	InputResponseView,
	ListResourcesCallback,
	McpServerDefinition,
	McpServerBuildContext,
	McpServerFeature,
	McpServerErrorCode,
	McpServerMiddleware,
	McpServerOperationInput,
	McpServerOperationContext,
	McpServerPrincipal,
	McpServerPrincipalClaims,
	McpServerPrincipalClaimsResolver,
	McpServerRuntimeEvent,
	McpServerRuntimeObserver,
	McpServerRuntimePhase,
	RegisteredPrompt,
	RegisteredResource,
	RegisteredResourceTemplate,
	RegisteredTool,
	ReadResourceCallback,
	ReadResourceResult,
	ReadResourceTemplateCallback,
	RequestStateCodec,
	RequestStateCodecOptions,
	ServerContext,
	ToolCallback,
} from "@nestm/mcp-server";

export {
	GatewayNameCodec,
	GatewayPromptNameCodec,
	GatewayResourceTemplateUriCodec,
	GatewayResourceUriCodec,
	InMemoryMcpGatewayDiscoveryCache,
	McpGateway,
	McpGatewayError,
	allowAllMcpGatewayPolicy,
	createMcpClientRuntimeUpstream,
	createMcpGateway,
	createMcpGatewayFeature,
	createMcpGatewayPassthroughMiddleware,
	defaultMcpGatewayAuthorizationContext,
	defineMcpGatewayTransform,
} from "@nestm/mcp-gateway";
export type {
	GatewayResourceTemplateUriCodecOptions,
	GatewayResourceUriCodecOptions,
	InMemoryMcpGatewayDiscoveryCacheOptions,
	McpGatewayAuthorizationContextResolver,
	McpGatewayCallToolOptions,
	McpGatewayClient,
	McpGatewayClientRequestOptions,
	McpGatewayClientResolver,
	McpGatewayClientRuntime,
	McpGatewayCompletionOperationInput,
	McpGatewayDecodedName,
	McpGatewayDecodedPromptName,
	McpGatewayDecodedResourceTemplateUri,
	McpGatewayDecodedResourceUri,
	McpGatewayDiscoveryCache,
	McpGatewayDiscoveryCacheKey,
	McpGatewayDiscoverySnapshot,
	McpGatewayDiscoveryOperationInput,
	McpGatewayInvocationOperationInput,
	McpGatewayLifecycleObserver,
	McpGatewayListPromptsResult,
	McpGatewayListResourceTemplatesResult,
	McpGatewayListResourcesResult,
	McpGatewayListToolsResult,
	McpGatewayMiddleware,
	McpGatewayNameCodec,
	McpGatewayOperationContext,
	McpGatewayOperationInput,
	McpGatewayOperationInputFor,
	McpGatewayOperationKind,
	McpGatewayOperationOutput,
	McpGatewayOperationOutputFor,
	McpGatewayOperationOutputForKind,
	McpGatewayOperationOutputMap,
	McpGatewayOptions,
	McpGatewayPassthroughMiddleware,
	McpGatewayPolicy,
	McpGatewayPolicyInput,
	McpGatewayPrincipal,
	McpGatewayReadonly,
	McpGatewayPromptNameCodec,
	McpGatewayPromptGetOperationInput,
	McpGatewayPromptPolicy,
	McpGatewayPromptPolicyInput,
	McpGatewayProjectedPrompt,
	McpGatewayProjectedResource,
	McpGatewayProjectedResourceTemplate,
	McpGatewayProjectedTool,
	McpGatewayRequestContext,
	McpGatewayResolvedRequestContext,
	McpGatewayResourcePolicy,
	McpGatewayResourcePolicyInput,
	McpGatewayResourceReadOperationInput,
	McpGatewayResourceTemplateDefinition,
	McpGatewayResourceTemplatePolicy,
	McpGatewayResourceTemplatePolicyInput,
	McpGatewayResourceTemplateReadOperationInput,
	McpGatewayResourceTemplateUriCodec,
	McpGatewayResourceUriCodec,
	McpGatewayToolClient,
	McpGatewayTransform,
	McpGatewayUpstream,
	McpGatewayErrorCode,
} from "@nestm/mcp-gateway";

export {
	MCP_METRIC_NAMES,
	MCP_TELEMETRY_DEFAULT_LIMITS,
	MCP_TELEMETRY_HARD_LIMITS,
	createMcpLoggerObserver,
	createMcpMetricsObserver,
	createMcpTracingMiddleware,
	projectMcpTelemetryAttributes,
} from "@nestm/mcp-observability";
export type {
	McpLoggerObserverOptions,
	McpLogLevel,
	McpMetricMeasurement,
	McpMetricKind,
	McpMetricNames,
	McpMetricsObserverOptions,
	McpMetricsSink,
	McpStructuredLogSink,
	McpStructuredLogRecord,
	McpTelemetryAttributeCandidate,
	McpTelemetryAttributeSource,
	McpTelemetryAttributeValue,
	McpTelemetryAttributes,
	McpTelemetryProjectionOptions,
	McpTraceSpan,
	McpTraceSpanKind,
	McpTraceSpanStatus,
	McpTraceStartOptions,
	McpTracer,
	McpTracingMiddlewareOptions,
	McpTracingPhase,
} from "@nestm/mcp-observability";

export { McpResourceServer, withMcpBearerAuth } from "@nestm/mcp-server/auth";
export type {
	McpFetchHandler,
	McpResourceServerOptions,
	OAuthTokenVerifier,
} from "@nestm/mcp-server/auth";
export { McpValidatedServer, withMcpRequestValidation } from "@nestm/mcp-server/security";
export type { McpRequestValidationOptions } from "@nestm/mcp-server/security";
