export {
	AuthorizationServerMismatchError,
	Client,
	ClientCredentialsProvider,
	CrossAppAccessProvider,
	InsecureTokenEndpointError,
	InsufficientScopeError,
	IssuerMismatchError,
	OAuthClientFlowError,
	PrivateKeyJwtProvider,
	RegistrationRejectedError,
	StaticPrivateKeyJwtProvider,
	StreamableHTTPClientTransport,
	UnauthorizedError,
	applyMiddlewares,
	auth,
	createPrivateKeyJwtAuth,
	createMiddleware,
	discoverOAuthMetadata,
	discoverOAuthProtectedResourceMetadata,
	discoverOAuthServerInfo,
	refreshAuthorization,
	isInputRequiredResult,
	specTypeSchemas,
	withInputRequired,
	withLogging,
	withOAuth,
} from "@modelcontextprotocol/client";
export type {
	AddClientAuthentication,
	AuthOptions,
	AuthProvider,
	AuthResult,
	ClientAuthMethod,
	ClientCredentialsProviderOptions,
	ClientOptions,
	CallToolRequest,
	CallToolRequestOptions,
	CallToolResult,
	CompleteRequest,
	CompleteResult,
	ConnectOptions,
	CrossAppAccessContext,
	CrossAppAccessProviderOptions,
	EmptyResult,
	FetchLike,
	LoggingOptions,
	LoggingLevel,
	GetPromptRequest,
	GetPromptResult,
	InputRequest,
	InputRequests,
	InputRequiredOptions,
	InputRequiredResult,
	InputResponse,
	InputResponses,
	McpSubscription,
	Middleware,
	Notification,
	NotificationOptions,
	OAuthClientInformationContext,
	OAuthClientProvider,
	OAuthDiscoveryState,
	OAuthServerInfo,
	PriorDiscovery,
	PrivateKeyJwtProviderOptions,
	RequestLogger,
	Request,
	RequestMethod,
	RequestOptions,
	RequestTypeMap,
	ReadResourceRequest,
	ReadResourceResult,
	ResultTypeMap,
	StandardSchemaV1,
	SubscribeRequest,
	SubscriptionFilter,
	StaticPrivateKeyJwtProviderOptions,
	StreamableHTTPClientTransportOptions,
	Transport,
	UnsubscribeRequest,
} from "@modelcontextprotocol/client";
export { StdioClientTransport } from "@modelcontextprotocol/client/stdio";
export type { StdioServerParameters } from "@modelcontextprotocol/client/stdio";

export {
	MCP_CLIENT_NOT_CONNECTED,
	MCP_CLIENT_RUNTIME_CLOSED,
	MCP_CLIENT_SERVER_EXISTS,
	MCP_CLIENT_SERVER_NOT_FOUND,
	MCP_CLIENT_SHUTDOWN_TIMEOUT,
	McpClientRuntimeError,
} from "./errors.ts";
export type { McpClientRuntimeErrorCode } from "./errors.ts";

export { McpClientRuntime } from "./runtime.ts";

export { createMcpClientToolSchema } from "./tool-schema.ts";
export type {
	McpClientToolSchema,
	McpClientToolSchemaIssue,
	McpClientToolSchemaResult,
	McpClientToolStandardSchema,
} from "./tool-schema.ts";

export {
	bindMcpClientMiddleware,
	createMcpClientPassthroughMiddleware,
	defineMcpClientTransform,
} from "./middleware.ts";

export {
	composeMcpFetchMiddleware,
	createMcpClientTransport,
	createMcpHttpClientTransport,
	createMcpStdioClientTransport,
	defaultMcpClientTransportFactory,
} from "./transport.ts";
export type {
	McpClientTransportDefinition,
	McpClientTransportFactory,
	McpClientTransportFactoryContext,
	McpHttpClientTransportDefinition,
	McpStdioClientTransportDefinition,
} from "./transport.ts";

export type {
	McpClientAttributesResolver,
	McpClientConfigurationContext,
	McpClientConfigurator,
	McpClientConnectionSnapshot,
	McpClientConnectionState,
	McpClientMiddleware,
	McpClientMrtrMethod,
	McpClientMrtrRequest,
	McpClientMrtrRequestOptions,
	McpClientMrtrResult,
	McpClientOperationContext,
	McpClientOperationInput,
	McpClientPassthroughMiddleware,
	McpClientPrincipalResolver,
	McpClientProtocolRequest,
	McpClientReadonly,
	McpClientRequestMethod,
	McpClientRuntimeOptions,
	McpClientServerDefinition,
	McpClientSubscription,
	McpClientTransform,
	McpClientTransformInput,
	McpClientTransformOptions,
	McpClientTransformResult,
	McpClientTool,
	McpClientToolInputSchema,
	McpClientToolOutputSchema,
	McpSdkClientFactory,
	McpSdkClientFactoryContext,
} from "./types.ts";
